//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCS.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Communication()
        {
            this.ReservationCommunications = new HashSet<ReservationCommunication>();
        }
    
        public int ID { get; set; }
        public string Content { get; set; }
        public bool IsAlert { get; set; }
        public Nullable<System.DateTime> RecievedOn { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationCommunication> ReservationCommunications { get; set; }
    }
}
