//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCS.Data.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMCSEntities : DbContext
    {
        public EMCSEntities()
            : base("name=EMCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetCategory> AssetCategories { get; set; }
        public virtual DbSet<AssetStatusSVT> AssetStatusSVTs { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImageType> ImageTypes { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<ReservationCommunication> ReservationCommunications { get; set; }
        public virtual DbSet<ReservationStatusHistory> ReservationStatusHistories { get; set; }
        public virtual DbSet<ReservationStatusSVT> ReservationStatusSVTs { get; set; }
        public virtual DbSet<Specification> Specifications { get; set; }
    }
}
