//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCS.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ID { get; set; }
        public System.Guid StorageKey { get; set; }
        public string FileName { get; set; }
        public int ImageSizeInKilobytes { get; set; }
        public string FormatDescription { get; set; }
        public string Description { get; set; }
        public int TypeID { get; set; }
        public int AssetID { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual ImageType ImageType { get; set; }
    }
}
