//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCS.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Notes = new HashSet<Note>();
            this.ReservationCommunications = new HashSet<ReservationCommunication>();
            this.ReservationStatusHistories = new HashSet<ReservationStatusHistory>();
        }
    
        public int ID { get; set; }
        public System.DateTime StartedOn { get; set; }
        public System.DateTime EndedOn { get; set; }
        public int ReservationNumber { get; set; }
        public int ReservedForID { get; set; }
        public Nullable<System.DateTime> CheckedOutOn { get; set; }
        public Nullable<System.DateTime> CheckedInOn { get; set; }
        public Nullable<System.DateTime> ExtensionEndsOn { get; set; }
        public Nullable<int> CheckedOutByID { get; set; }
        public Nullable<int> CheckedInByID { get; set; }
        public Nullable<int> PickedUpByID { get; set; }
        public Nullable<int> ReturnedByID { get; set; }
        public int AssetID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Asset Asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ReservationStatusSVT ReservationStatusSVT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationCommunication> ReservationCommunications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationStatusHistory> ReservationStatusHistories { get; set; }
    }
}
