//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCS.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationStatusHistory
    {
        public int ID { get; set; }
        public System.DateTime StatusChangedOn { get; set; }
        public int ReservationID { get; set; }
        public int ReservationStatusID { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual ReservationStatusSVT ReservationStatusSVT { get; set; }
    }
}
